// Placeholder data for Gokul Vivaham frontend UI

export interface Profile {
  id: number;
  name: string;
  gender: "Male" | "Female";
  age: number;
  location: string;
  religion: string;
  caste: string;
  motherTongue: string;
  maritalStatus: string;
  height: string;
  weight: string;
  education: string;
  degree: string;
  institution: string;
  profession: string;
  occupation: string;
  annualIncome: string;
  rasi: string;
  nakshatra: string;
  lagnam: string;
  gothram: string;
  patham: number;
  doshams: string[];
  rasiChart: string[]; // 12 elements starting from Pisces (top-left) clockwise
  aboutMe: string;
  familyDetails: {
    fatherName: string;
    fatherOccupation: string;
    motherName: string;
    motherOccupation: string;
    siblings: string;
    familyValues: "Orthodox" | "Traditional" | "Moderate" | "Liberal";
    familyStatus: "Middle Class" | "Upper Middle Class" | "Rich";
  };
  expectations: {
    ageRange: string;
    heightRange: string;
    education: string;
    profession: string;
    location: string;
    rasi: string;
  };
  images: string[];
  verified: boolean;
  premium: boolean;
}

export const mockProfiles: Profile[] = [
  {
    id: 1,
    name: "Priya Lakshmi",
    gender: "Female",
    age: 26,
    location: "Chennai, Tamil Nadu",
    religion: "Hindu",
    caste: "Iyer",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 4\"",
    weight: "55 kg",
    education: "Post Graduate",
    degree: "M.Tech - Computer Science",
    institution: "IIT Madras",
    profession: "Software Job",
    occupation: "Senior Software Engineer",
    annualIncome: "₹18,00,000",
    rasi: "Rishabam",
    nakshatra: "Krithigai",
    lagnam: "Simham",
    gothram: "Bharadwaj",
    patham: 2,
    doshams: ["None"],
    rasiChart: ["Sani", "Lagnam", "Rahu", "", "", "Guru", "Kethu", "", "Suriyan", "Chandran", "Sevvai", "Budhan"],
    aboutMe: "I am a warm, ambitious person who loves technology, Carnatic music, and classic literature. I balance traditional Tamil values with a modern outlook on life. Looking for a partner who is intellectual, caring, and values family ties.",
    familyDetails: {
      fatherName: "K. R. Ramakrishnan",
      fatherOccupation: "Retired Bank Manager",
      motherName: "Saraswathi Ramakrishnan",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Brother (Studying B.E)",
      familyValues: "Traditional",
      familyStatus: "Upper Middle Class",
    },
    expectations: {
      ageRange: "27 - 31 years",
      heightRange: "5' 7\" to 6' 0\"",
      education: "B.E/B.Tech, MS, MBA or PhD",
      profession: "Software Engineer, Doctor, or Manager",
      location: "Chennai, Bangalore, or USA",
      rasi: "Mithunam, Kanni, or Simham preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
  {
    id: 2,
    name: "Kavitha Sundaram",
    gender: "Female",
    age: 24,
    location: "Coimbatore, Tamil Nadu",
    religion: "Hindu",
    caste: "Gounder",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 2\"",
    weight: "52 kg",
    education: "Post Graduate",
    degree: "MBA - Finance",
    institution: "Anna University",
    profession: "Corporate Job",
    occupation: "Business Analyst",
    annualIncome: "₹8,50,000",
    rasi: "Mithunam",
    nakshatra: "Thiruvadhirai",
    lagnam: "Kanni",
    gothram: "Siva",
    patham: 1,
    doshams: ["Chevvai Dosham (Mild)"],
    rasiChart: ["Guru", "", "", "Rahu", "Sevvai", "Lagnam", "", "", "Sani", "Budhan", "Suriyan", "Kethu"],
    aboutMe: "Friendly and down-to-earth person who loves exploring new cafes and volunteering for social causes. I believe in mutual respect and clear communication in a marriage. Looking for someone with a stable career and positive mindset.",
    familyDetails: {
      fatherName: "S. Sundaramoorthy",
      fatherOccupation: "Agriculturist & Business Owner",
      motherName: "Indrani Sundaramoorthy",
      motherOccupation: "Homemaker",
      siblings: "1 Elder Sister (Married)",
      familyValues: "Moderate",
      familyStatus: "Middle Class",
    },
    expectations: {
      ageRange: "26 - 29 years",
      heightRange: "5' 5\" to 5' 10\"",
      education: "Any Degree or Post Graduate",
      profession: "Business Owner, IT Employee, or Govt Job",
      location: "Coimbatore or nearby districts",
      rasi: "Mesham, Rishabam preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1594744803329-e58b31de215f?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: false,
  },
  {
    id: 3,
    name: "Meena Krishnan",
    gender: "Female",
    age: 27,
    location: "Madurai, Tamil Nadu",
    religion: "Hindu",
    caste: "Pillai",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 3\"",
    weight: "54 kg",
    education: "Doctorate/Medical",
    degree: "MBBS, MD - Pediatrics",
    institution: "Madurai Medical College",
    profession: "Medical Professional",
    occupation: "Consultant Pediatrician",
    annualIncome: "₹15,00,000",
    rasi: "Kanni",
    nakshatra: "Uthiram",
    lagnam: "Mesham",
    gothram: "Vishnu",
    patham: 3,
    doshams: ["None"],
    rasiChart: ["", "Lagnam", "", "", "Sani", "Rahu", "Guru", "Budhan", "Suriyan", "", "Sevvai", "Kethu"],
    aboutMe: "Caring doctor dedicated to child healthcare. In my spare time, I practice Bharathanatyam and enjoy culinary arts. I seek a life partner who is equally dedicated to their work but keeps family first.",
    familyDetails: {
      fatherName: "Dr. R. Krishnan",
      fatherOccupation: "Chief Medical Officer",
      motherName: "Dr. Radhika Krishnan",
      motherOccupation: "Gynaecologist",
      siblings: "No siblings (Only child)",
      familyValues: "Moderate",
      familyStatus: "Rich",
    },
    expectations: {
      ageRange: "28 - 32 years",
      heightRange: "5' 6\" to 6' 0\"",
      education: "Doctor, Engineer, or Management",
      profession: "Medical or Highly Qualified Professional",
      location: "Tamil Nadu",
      rasi: "Kanni, Thula, Dhanusu preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
  {
    id: 4,
    name: "Anitha Rajan",
    gender: "Female",
    age: 25,
    location: "Trichy, Tamil Nadu",
    religion: "Hindu",
    caste: "Mudaliar",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 5\"",
    weight: "58 kg",
    education: "Graduate",
    degree: "B.E - Civil Engineering",
    institution: "PSG College of Technology",
    profession: "Civil Engineer",
    occupation: "Project Engineer",
    annualIncome: "₹7,20,000",
    rasi: "Thula",
    nakshatra: "Swathi",
    lagnam: "Dhanusu",
    gothram: "Siva",
    patham: 4,
    doshams: ["Rahu-Kethu Dosham"],
    rasiChart: ["Rahu", "", "Budhan", "Suriyan", "", "", "Lagnam", "Kethu", "", "Sani", "Sevvai", "Guru"],
    aboutMe: "An active, fun-loving person who is passionate about architecture and interior design. I love traveling and photography. Looking for a partner who is supportive, open-minded, and shares an interest in exploring new places.",
    familyDetails: {
      fatherName: "M. Rajan",
      fatherOccupation: "PWD Contractor",
      motherName: "Kamala Rajan",
      motherOccupation: "Government High School Teacher",
      siblings: "1 Elder Brother (Software Engineer in Bangalore)",
      familyValues: "Moderate",
      familyStatus: "Middle Class",
    },
    expectations: {
      ageRange: "27 - 30 years",
      heightRange: "5' 7\" to 5' 11\"",
      education: "B.E/B.Tech, MCA, MBA",
      profession: "Engineering, Banking, or Government Sector",
      location: "Tamil Nadu or Bangalore",
      rasi: "Thula, Kumbham preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?q=80&w=600&auto=format&fit=crop",
    ],
    verified: false,
    premium: false,
  },
  {
    id: 5,
    name: "Divya Murugan",
    gender: "Female",
    age: 28,
    location: "Tirunelveli, Tamil Nadu",
    religion: "Hindu",
    caste: "Naicker",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 6\"",
    weight: "57 kg",
    education: "Post Graduate",
    degree: "M.Sc - Biotechnology",
    institution: "Bharathidasan University",
    profession: "Research Scientist",
    occupation: "Associate Scientist",
    annualIncome: "₹12,00,000",
    rasi: "Karkadagam",
    nakshatra: "Poosam",
    lagnam: "Makaram",
    gothram: "Kasyapa",
    patham: 2,
    doshams: ["None"],
    rasiChart: ["Budhan", "Suriyan", "", "", "Rahu", "Lagnam", "", "", "Guru", "Sani", "Kethu", "Sevvai"],
    aboutMe: "A focused researcher, nature enthusiast, and occasional hiker. I value simplicity and authenticity. Seeking a life companion who has a logical mind, respects elders, and has a good sense of humor.",
    familyDetails: {
      fatherName: "T. Murugan",
      fatherOccupation: "Retail Shop Owner",
      motherName: "Srimathi Murugan",
      motherOccupation: "Homemaker",
      siblings: "2 Younger Sisters (Unmarried)",
      familyValues: "Traditional",
      familyStatus: "Middle Class",
    },
    expectations: {
      ageRange: "29 - 33 years",
      heightRange: "5' 8\" to 6' 1\"",
      education: "Post Graduate or PhD",
      profession: "Scientist, Professor, or Senior Professional",
      location: "Tamil Nadu, Chennai, or Overseas",
      rasi: "Karkadagam, Makaram, Meenam preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
  {
    id: 6,
    name: "Suganya Palanisamy",
    gender: "Female",
    age: 23,
    location: "Salem, Tamil Nadu",
    religion: "Hindu",
    caste: "Vanniyar",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 1\"",
    weight: "48 kg",
    education: "Graduate",
    degree: "B.Com, Chartered Accountant",
    institution: "Periyar University",
    profession: "Chartered Accountant",
    occupation: "Financial Auditor",
    annualIncome: "₹10,50,000",
    rasi: "Makaram",
    nakshatra: "Uthiradam",
    lagnam: "Kumbham",
    gothram: "Siva",
    patham: 3,
    doshams: ["None"],
    rasiChart: ["", "Lagnam", "", "", "Sani", "Rahu", "Guru", "Budhan", "Suriyan", "", "Sevvai", "Kethu"],
    aboutMe: "I am a young, dedicated Chartered Accountant. I enjoy cooking, classical dance, and family gatherings. I am looking for a partner who is mature, family-oriented, and residing in Tamil Nadu.",
    familyDetails: {
      fatherName: "V. Palanisamy",
      fatherOccupation: "Government Contractor",
      motherName: "Senthil Vadivu Palanisamy",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Brother (Studying CA Intermediate)",
      familyValues: "Orthodox",
      familyStatus: "Upper Middle Class",
    },
    expectations: {
      ageRange: "25 - 28 years",
      heightRange: "5' 5\" to 5' 10\"",
      education: "CA, MBA, B.E/B.Tech",
      profession: "CA, Banker, IT Professional, or Civil Servant",
      location: "Tamil Nadu (Coimbatore, Salem, Erode preferred)",
      rasi: "Kumbham, Simham preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1548142813-c348350df52b?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: false,
  },
  {
    id: 7,
    name: "Rajesh Kumar",
    gender: "Male",
    age: 28,
    location: "Chennai, Tamil Nadu",
    religion: "Hindu",
    caste: "Mudaliar",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 9\"",
    weight: "72 kg",
    education: "Graduate",
    degree: "B.E - Computer Science",
    institution: "College of Engineering, Guindy",
    profession: "Software Job",
    occupation: "Tech Lead",
    annualIncome: "₹24,00,000",
    rasi: "Simham",
    nakshatra: "Magam",
    lagnam: "Dhanusu",
    gothram: "Kasyapa",
    patham: 2,
    doshams: ["None"],
    rasiChart: ["Guru", "", "", "Rahu", "Sevvai", "Lagnam", "", "", "Sani", "Budhan", "Suriyan", "Kethu"],
    aboutMe: "Hi, I am Rajesh. I work as a Tech Lead in a multinational IT firm. I love traveling, playing badminton, and photography. I am an optimistic person who values family ethics alongside career growth. Looking for a partner who is independent, educated, and matches my vibe.",
    familyDetails: {
      fatherName: "K. Kumar",
      fatherOccupation: "Retired PWD Engineer",
      motherName: "Mangalam Kumar",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Sister (Married)",
      familyValues: "Moderate",
      familyStatus: "Upper Middle Class",
    },
    expectations: {
      ageRange: "23 - 27 years",
      heightRange: "5' 2\" to 5' 7\"",
      education: "Graduate or Post Graduate",
      profession: "IT Professional, Banker, or Architect",
      location: "Chennai or Bangalore",
      rasi: "Simham, Rishabam, Mithunam preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
  {
    id: 8,
    name: "Karthik Venkat",
    gender: "Male",
    age: 29,
    location: "Bangalore, Karnataka",
    religion: "Hindu",
    caste: "Iyer",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 11\"",
    weight: "78 kg",
    education: "Post Graduate",
    degree: "MS in Data Science",
    institution: "BITS Pilani",
    profession: "Software Job",
    occupation: "Senior Data Scientist",
    annualIncome: "₹30,00,000",
    rasi: "Mithunam",
    nakshatra: "Thiruvadhirai",
    lagnam: "Kanni",
    gothram: "Vatsa",
    patham: 4,
    doshams: ["Chevvai Dosham (Mild)"],
    rasiChart: ["Lagnam", "Budhan", "Suriyan", "Kethu", "", "", "Sani", "", "Rahu", "Sevvai", "Guru", "Chandran"],
    aboutMe: "I am an outgoing person, passionate about AI, cycling, and playing guitar. I enjoy weekend road trips and cooking. Looking for an educated, career-oriented Iyer bride who is cheerful and shares a mutual appreciation for art and sciences.",
    familyDetails: {
      fatherName: "V. Venkataraman",
      fatherOccupation: "Financial Consultant",
      motherName: "Geetha Venkataraman",
      motherOccupation: "Vocal Music Teacher",
      siblings: "1 Elder Brother (Software Architect in Seattle, USA)",
      familyValues: "Traditional",
      familyStatus: "Upper Middle Class",
    },
    expectations: {
      ageRange: "24 - 28 years",
      heightRange: "5' 4\" to 5' 9\"",
      education: "B.E/B.Tech, MBA, MS",
      profession: "Working Professional",
      location: "Bangalore, Chennai, or Hyderabad",
      rasi: "Mithunam, Rishabam, Kanni preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
  {
    id: 9,
    name: "Suresh Raman",
    gender: "Male",
    age: 31,
    location: "Coimbatore, Tamil Nadu",
    religion: "Hindu",
    caste: "Gounder",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 8\"",
    weight: "74 kg",
    education: "Graduate",
    degree: "B.E - Mech Engineering",
    institution: "PSG Tech",
    profession: "Business Owner",
    occupation: "Manufacturing Industry Owner",
    annualIncome: "₹35,00,000",
    rasi: "Mesham",
    nakshatra: "Aswini",
    lagnam: "Karkadagam",
    gothram: "Siva",
    patham: 3,
    doshams: ["None"],
    rasiChart: ["Budhan", "Suriyan", "Sevvai", "Guru", "Lagnam", "", "", "Sani", "Rahu", "", "", "Kethu"],
    aboutMe: "I manage our family textile machinery manufacturing business. I am deeply rooted in Tamil culture, love farming, and enjoy traditional food. Looking for a family-oriented girl who can manage home and support my ventures.",
    familyDetails: {
      fatherName: "S. Ramanathan",
      fatherOccupation: "Industrialist",
      motherName: "Saradha Ramanathan",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Brother (Managing Business)",
      familyValues: "Traditional",
      familyStatus: "Rich",
    },
    expectations: {
      ageRange: "24 - 28 years",
      heightRange: "5' 2\" to 5' 6\"",
      education: "Graduate or above",
      profession: "Homemaker or Career-Oriented (Choice is hers)",
      location: "Coimbatore, Tiruppur, Erode",
      rasi: "Mesham, Dhanusu preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: false,
  },
  {
    id: 10,
    name: "Arun Prasath",
    gender: "Male",
    age: 27,
    location: "Madurai, Tamil Nadu",
    religion: "Hindu",
    caste: "Pillai",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 10\"",
    weight: "70 kg",
    education: "Graduate",
    degree: "B.Tech - Information Technology",
    institution: "TCE Madurai",
    profession: "Software Job",
    occupation: "Full Stack Developer",
    annualIncome: "₹12,00,000",
    rasi: "Vrishchikam",
    nakshatra: "Anusham",
    lagnam: "Kumbham",
    gothram: "Vishnu",
    patham: 1,
    doshams: ["None"],
    rasiChart: ["", "Lagnam", "", "", "Sani", "Rahu", "Guru", "Budhan", "Suriyan", "", "Sevvai", "Kethu"],
    aboutMe: "I am a simple, honest person who loves coding, blogging, and playing cricket. I believe that marriage is a partnership of equals. Looking for a partner who is supportive, friendly, and shares positive values.",
    familyDetails: {
      fatherName: "A. Prasath",
      fatherOccupation: "Government Clerk",
      motherName: "Soundara Prasath",
      motherOccupation: "Homemaker",
      siblings: "1 Elder Sister (Married)",
      familyValues: "Moderate",
      familyStatus: "Middle Class",
    },
    expectations: {
      ageRange: "22 - 26 years",
      heightRange: "5' 1\" to 5' 6\"",
      education: "Any Graduate",
      profession: "IT Job, Teaching, or Bank Sector",
      location: "Madurai, Trichy, or Chennai",
      rasi: "Kanni, Vrishchikam preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1489980508314-941910ded1f4?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: false,
  },
  {
    id: 11,
    name: "Vignesh Balaji",
    gender: "Male",
    age: 26,
    location: "Chennai, Tamil Nadu",
    religion: "Hindu",
    caste: "Naicker",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "5' 8\"",
    weight: "68 kg",
    education: "Post Graduate",
    degree: "M.Sc - Computer Science",
    institution: "Loyola College, Chennai",
    profession: "Software Job",
    occupation: "UX Designer",
    annualIncome: "₹9,50,000",
    rasi: "Kumbham",
    nakshatra: "Sadhayam",
    lagnam: "Mesham",
    gothram: "Siva",
    patham: 2,
    doshams: ["Rahu-Kethu Dosham"],
    rasiChart: ["Rahu", "", "Budhan", "Suriyan", "", "", "Lagnam", "Kethu", "", "Sani", "Sevvai", "Guru"],
    aboutMe: "Creative designer, movie buff, and travel blogger. I love sketching and learning about traditional architectures. Seeking an open-minded partner who has creative interests and believes in enjoying life to the fullest.",
    familyDetails: {
      fatherName: "S. Balaji",
      fatherOccupation: "Postmaster",
      motherName: "Kokila Balaji",
      motherOccupation: "Homemaker",
      siblings: "No siblings",
      familyValues: "Liberal",
      familyStatus: "Middle Class",
    },
    expectations: {
      ageRange: "22 - 25 years",
      heightRange: "5' 0\" to 5' 6\"",
      education: "Graduate in Arts, Science, or Engineering",
      profession: "Creative fields, IT, or Media preferred",
      location: "Chennai",
      rasi: "Kumbham, Thula preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop",
    ],
    verified: false,
    premium: true,
  },
  {
    id: 12,
    name: "Deepak Chandran",
    gender: "Male",
    age: 30,
    location: "Singapore",
    religion: "Hindu",
    caste: "Vanniyar",
    motherTongue: "Tamil",
    maritalStatus: "Never Married",
    height: "6' 0\"",
    weight: "82 kg",
    education: "Post Graduate",
    degree: "MBA - Global Finance",
    institution: "NUS Singapore",
    profession: "Corporate Job",
    occupation: "Investment Analyst",
    annualIncome: "S$85,00,000 (Approx ₹50,00,000)",
    rasi: "Rishabam",
    nakshatra: "Rohini",
    lagnam: "Thula",
    gothram: "Bharadwaj",
    patham: 4,
    doshams: ["None"],
    rasiChart: ["Sani", "Lagnam", "Rahu", "", "", "Guru", "Kethu", "", "Suriyan", "Chandran", "Sevvai", "Budhan"],
    aboutMe: "Living and working in Singapore for the past 6 years. I am a fitness enthusiast, marathon runner, and love cooking South Indian food. I value family relationships and look for a bride willing to relocate to Singapore.",
    familyDetails: {
      fatherName: "Dr. P. Chandran",
      fatherOccupation: "Professor (Retired)",
      motherName: "Suseela Chandran",
      motherOccupation: "Retired School Principal",
      siblings: "1 Elder Sister (Married and settled in UK)",
      familyValues: "Moderate",
      familyStatus: "Upper Middle Class",
    },
    expectations: {
      ageRange: "25 - 29 years",
      heightRange: "5' 3\" to 5' 8\"",
      education: "Graduate / Post Graduate",
      profession: "Any professional career",
      location: "Willing to relocate to Singapore",
      rasi: "Rishabam, Kanni preferred",
    },
    images: [
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&auto=format&fit=crop",
    ],
    verified: true,
    premium: true,
  },
];

// Fallback subset for backwards compatibility
export const featuredProfiles = mockProfiles
  .filter((p) => p.gender === "Female")
  .map((p) => ({
    id: p.id,
    name: p.name,
    age: p.age,
    location: p.location,
    education: p.degree,
    profession: p.occupation,
    rasi: p.rasi,
    nakshatra: p.nakshatra,
    image: p.images[0],
    verified: p.verified,
    premium: p.premium,
  }));

export const successStories = [
  {
    id: 1,
    bride: "Karthika",
    groom: "Aravind",
    location: "Chennai",
    date: "December 2024",
    story:
      "We found each other on Gokul Vivaham and instantly connected over our shared love for Carnatic music. Today, we are happily married and grateful for this platform.",
    brideImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=karthika&backgroundColor=ffd5dc",
    groomImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=aravind&backgroundColor=b6e3f4",
    rating: 5,
  },
  {
    id: 2,
    bride: "Saranya",
    groom: "Vijay",
    location: "Coimbatore",
    date: "March 2025",
    story:
      "I was skeptical about online matrimony but Gokul Vivaham's verified profiles gave me confidence. Within 3 months, I found my life partner. Best decision ever!",
    brideImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=saranya&backgroundColor=c0aede",
    groomImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=vijay&backgroundColor=b6efca",
    rating: 5,
  },
  {
    id: 3,
    bride: "Nithya",
    groom: "Senthil",
    location: "Singapore",
    date: "January 2025",
    story:
      "Living abroad made it hard to find a Tamil match. Gokul Vivaham connected us across continents. We are now settled in Singapore and couldn't be happier.",
    brideImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=nithya&backgroundColor=ffdfbf",
    groomImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=senthil&backgroundColor=d1d4f9",
    rating: 5,
  },
];

export const membershipPlans = [
  {
    id: 1,
    name: "Silver",
    nameInTamil: "வெள்ளி",
    price: 999,
    duration: "3 months",
    color: "silver",
    features: [
      "50 Profile Views per Day",
      "Basic Search Filters",
      "Send 10 Interests/Day",
      "Photo Privacy Control",
      "Email Support",
    ],
    notIncluded: [
      "Direct Contact Access",
      "Horoscope Match",
      "AI Match Suggestions",
      "Priority Listing",
    ],
    popular: false,
  },
  {
    id: 2,
    name: "Gold",
    nameInTamil: "தங்கம்",
    price: 2499,
    duration: "6 months",
    color: "gold",
    features: [
      "Unlimited Profile Views",
      "Advanced Search Filters",
      "Send Unlimited Interests",
      "Direct Contact Access",
      "Horoscope Matching",
      "Photo & Video Profiles",
      "Priority Customer Support",
    ],
    notIncluded: ["AI Match Suggestions", "Priority Listing"],
    popular: true,
  },
  {
    id: 3,
    name: "Platinum",
    nameInTamil: "பிளாட்டினம்",
    price: 4999,
    duration: "12 months",
    color: "platinum",
    features: [
      "All Gold Features",
      "AI-Powered Match Suggestions",
      "Priority Profile Listing",
      "Dedicated Relationship Manager",
      "Astrological Consultation",
      "Profile Highlight Badge",
      "24/7 Premium Support",
      "Offline Event Invitations",
    ],
    notIncluded: [],
    popular: false,
  },
];

export const whyChooseUs = [
  {
    id: 1,
    icon: "shield-check",
    title: "100% Verified Profiles",
    description:
      "Every profile is manually verified with government ID, ensuring authentic and genuine matches for your safety.",
  },
  {
    id: 2,
    icon: "star",
    title: "Jathagam Matching",
    description:
      "Advanced horoscope compatibility matching using traditional Tamil astrology for perfect astrological alignment.",
  },
  {
    id: 3,
    icon: "users",
    title: "500,000+ Profiles",
    description:
      "The largest Tamil matrimony database with profiles from Tamil Nadu, across India, and worldwide Tamil diaspora.",
  },
  {
    id: 4,
    icon: "heart",
    title: "50,000+ Marriages",
    description:
      "Proudly facilitated over 50,000 successful Tamil marriages since 2010 — your love story is next.",
  },
  {
    id: 5,
    icon: "globe",
    title: "Global Tamil Network",
    description:
      "Connect with Tamil profiles from India, USA, UK, Canada, Singapore, UAE, and 50+ countries worldwide.",
  },
  {
    id: 6,
    icon: "lock",
    title: "Privacy Protected",
    description:
      "Your personal data is encrypted and protected. Control who sees your contact info and photos.",
  },
];

export const navLinks = [
  { name: "Home", href: "/" },
  { name: "Search", href: "/search" },
  { name: "Dashboard", href: "/dashboard" },
  { name: "Membership", href: "/membership" },
  { name: "Success Stories", href: "/success-stories" },
];

export const footerLinks = {
  quickLinks: [
    { name: "Dashboard", href: "/dashboard" },
    { name: "Browse Profiles", href: "/search" },
    { name: "Premium Membership", href: "/membership" },
    { name: "Success Stories", href: "/success-stories" },
    { name: "Help & Support", href: "/support" },
  ],
  legal: [
    { name: "Privacy Policy", href: "/privacy" },
    { name: "Terms of Service", href: "/terms" },
    { name: "Cookie Policy", href: "/cookies" },
    { name: "Refund Policy", href: "/refund" },
  ],
  contact: {
    email: "support@gokulvivaham.com",
    phone: "+91 98765 43210",
    address: "No. 42, Anna Salai, Chennai — 600 002, Tamil Nadu",
    whatsapp: "+91 98765 43210",
  },
};

export const stats = [
  { value: "5,00,000+", label: "Verified Profiles" },
  { value: "50,000+", label: "Successful Marriages" },
  { value: "15+", label: "Years of Trust" },
  { value: "50+", label: "Countries Served" },
];
